name: TODOUI Pipeline

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - development
  #   paths:
  #     - main

jobs:
  CI:
    name: Build Application
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          
      # - name: nodejs install
      #   run: |
      #     curl -s https://deb.nodesource.com/setup_16.x | sudo bash
      #     sudo apt install nodejs -y
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.x
          cache: npm
          cache-dependency-path: package-lock.json
          
          
      - name: dependancies
        run: npm install

      - name: build artifacts
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/
           
        
